### ISSUE TITLE
NullPointerException in WidgetTimetableService.java

### ISSUE THREAD

**Issue by samstone86** [HTWDD/HTWDD#31]
Ich habe mal einen Auszug aus meinem logcat für euch:
```
12-11 21:20:09.888 I/ActivityManager(1535): Killing 5130:de.htwdd/u0a77 (adj 16): remove task
12-11 21:20:09.947 W/ActivityManager(1535): Scheduling restart of crashed service de.htwdd/.WidgetTimetableService in 1000ms
12-11 21:20:10.973 I/ActivityManager(1535): Start proc 9200:de.htwdd/u0a77 for service de.htwdd/.WidgetTimetableService
12-11 21:20:11.012 W/System  (9200): ClassLoader referenced unknown path: /data/app/de.htwdd-1/lib/arm
12-11 21:20:11.015 D/AndroidRuntime(9200): Shutting down VM
--------- beginning of crash
12-11 21:20:11.016 E/AndroidRuntime(9200): FATAL EXCEPTION: main
12-11 21:20:11.016 E/AndroidRuntime(9200): Process: de.htwdd, PID: 9200
12-11 21:20:11.016 E/AndroidRuntime(9200): java.lang.RuntimeException: Unable to start service de.htwdd.WidgetTimetableService@ecadb00 with null: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Bundle android.content.Intent.getExtras()' on a null object reference
12-11 21:20:11.016 E/AndroidRuntime(9200): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3027)
12-11 21:20:11.016 E/AndroidRuntime(9200): 	at android.app.ActivityThread.-wrap17(ActivityThread.java)
12-11 21:20:11.016 E/AndroidRuntime(9200): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1442)
12-11 21:20:11.016 E/AndroidRuntime(9200): 	at android.os.Handler.dispatchMessage(Handler.java:102)
12-11 21:20:11.016 E/AndroidRuntime(9200): 	at android.os.Looper.loop(Looper.java:148)
12-11 21:20:11.016 E/AndroidRuntime(9200): 	at android.app.ActivityThread.main(ActivityThread.java:5417)
12-11 21:20:11.016 E/AndroidRuntime(9200): 	at java.lang.reflect.Method.invoke(Native Method)
12-11 21:20:11.016 E/AndroidRuntime(9200): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
12-11 21:20:11.016 E/AndroidRuntime(9200): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
12-11 21:20:11.016 E/AndroidRuntime(9200): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Bundle android.content.Intent.getExtras()' on a null object reference
12-11 21:20:11.016 E/AndroidRuntime(9200): 	at de.htwdd.WidgetTimetableService.onStartCommand(WidgetTimetableService.java:37)
12-11 21:20:11.016 E/AndroidRuntime(9200): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3010)
12-11 21:20:11.016 E/AndroidRuntime(9200): 	... 8 more

12-11 21:20:20.945 I/ActivityManager(1535): Process de.htwdd (pid 9200) has died
12-11 21:20:20.946 W/ActivityManager(1535): Scheduling restart of crashed service de.htwdd/.WidgetTimetableService in 1000ms
```
aus irgendwelchen Gründen stürzt es ab und beim restart hat er nicht den richtigen Intend. 

Vielleicht einen check einbauen ob der Intent noch stimmt und ansonsten den Service nicht starten?

**Comment by FestPlatin** [comment]
Hey vielen Dank für deine Rückmeldung.

Kannst du den Absturz irgendwie reproduzieren?

Eine Überprüfung ob der "Intend" richtig ist und dann den Service ggf. nicht starten, sollte keine Lösung sein, da dann die Widgtes ja nicht mehr aktualisiert werden.

**Comment by samstone86** [comment]
Meistens wenn ich laufende Apps aus den recents rauswerfe und es ist egal welche App. Meistens so nach 4-6 Apps beendet such dann die HTW App.

**Comment by FestPlatin** [comment]
OK, ich konnte es nachstellen. Es reicht wenn die HTWDresden App beendet wird.

**Comment by samstone86** [comment]
Sollte laut logcat wirklich am Intent liegen habe mit einem Developer drüber geschaut und wenn wir nichts übersehen haben sollte es genau deswegen abstürzen

**Comment by FestPlatin** [comment]
Das der Intent beim neustarten des Service null ist, scheint laut Doku Standardverhalten zu sein. Von daher reicht wirklich eine einfache Überprüfung aus.

Kannst du bitte die [aktuelle](http://www2.htw-dresden.de/~s71513/HTWDD/HTWDresden-3.81_Bugfix.apk) Version mal testen.

**Comment by samstone86** [comment]
Mach ich

**Comment by samstone86** [comment]
Also erstmal alles ok ich melde mich Dienstag oder so nochmal . das sollte genug test Zeit sein

**Comment by samstone86** [comment]
Sieht gut aus tritt nicht mehr auf :-)
